### PR TITLE
Adds charlotte to the participants list

### PR DESCRIPTION
**Pull request by monoamro**
Thank you for registering for Codefreeze. Before you continue, please review our [Code of Conduct](https://codefreeze.fi/#code-of-conduct) carefully and mark an `x` inside the square brackets `[]` below to indicate your commitment to follow it.

- [x] I have read and understood the Code of Conduct.
- [x] I will make sure to educate the people who are travelling with me about the Code of Conduct.

### CODE REVIEW

**Comment by coderbyheart** [comment]
I've asked Charlotte to confirm this.

**Comment by monoamro** [comment]
Great!

**Comment by coderbyheart** [comment]
Charlotte confirmed this via email.
We care deeply about creating a safe and welcoming event for everyone, so please excuse for double checking.

**Comment by coderbyheart** [comment]
Montaser-Amro

Uploading here to link from website

**Comment by coderbyheart** [comment]
<details>
 <summary>Uploading image to link from website.</summary>

Charlotte-Oetken

</details>

**Comment by monoamro** [comment]
Should I update this and create a new PR? @coderbyheart

**Comment by coderbyheart** [comment]
No, I've fixed that. The way we include images is a little inconvenient.

See 85fa1d254760bd91479b78a3963c3155d87ba03d

**Comment by monoamro** [comment]
Ah I see, I had to hard refresh the website to see the changes! Anyway, glad it worked and very looking forward to it!!!

**Pull request merged**
